#!/usr/bin/env bash
# Configures a custom 404 page
sudo apt-get -y update
sudo apt-get -y install nginx
HEAD="\t\tadd_header X-Served-By $HOSTNAME;"
sudo sed -i "42i\ $HEAD" /etc/nginx/sites-available/default
sudo service nginx restart
