#!/usr/bin/env bash
# Install load balancer


CFG="\\\nlisten appname 0.0.0.0:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 531-web-01 34.73.123.158 check\n\tserver 531-web-02 34.73.111.24 check\n"
sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get install -y haproxy=1.8\*
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo sed -i "\$a $CFG" /etc/haproxy/haproxy.cfg
sudo service haproxy start
