#!/usr/bin/env bash
#Install load balancer

ENDS="frontend hbnb\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n\nbackend backendnodes\n\tbalance roundrobin\n\tserver 531-web-01 34.73.123.158:80 check\n\tserver 531-web-02 34.73.111.24:80 check"
sudo apt-get -y update
sudo apt-get -y install nginx
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy=1.8.\*
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo sed -i "\$a $ENDS" /etc/haproxy/haproxy.cfg
sudo service haproxy start
