#!/usr/bin/env bash
# Install load balancer

apt-get update
apt-get -y install haproxy
sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
echo "
frontend localserv
         bind *:80
         mode http
         default_backend webservs
backend webservs
        mode http
        balance roundrobin
        server 531-web-01 34.73.145.109:80
        server 532-web-02 35.196.46.86:80
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
