#!/usr/bin/env bash
# Script creates file '/var/run/holbertonscript.pid' containing its PID
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file and terminates upong SIGQUIT or SIGTERM signals

zurgT()
{
	echo I hate the kill command
	sudo rm -f /var/run/holbertonscript.pid
	exit 1
}
zurgQ()
{
	sudo rm -f /var/run/holbertonscript.pid
}
zurgI()
{
	echo Y U no love me?!
}

echo $$ > /var/run/holbertonscript.pid
trap zurgT SIGTERM
trap zurgQ SIGQUIT
trap zurgI SIGINT
while :
do
	echo To infinity and beyond
	sleep 2
done
