#!/usr/bin/env bash
# Manages manage_my_process bash script

if [ "$1" == "start" ]
then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	pkill -f "./manage_my_process"
	rm -f /var/run/my_process.pid
	rm -f /tmp/my_process
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	pkill -f "./manage_my_process"
	rm -f /var/run/my_process.pid
	rm -f /tmp/my_process
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
