#!/usr/bin/env bash
# Script displays the content of /etc/passwd file
# Displays username, user id, user home directory path

while read -r line; do
	echo "$line" | cut -d ':' -f 1,3,6
done < "/etc/passwd"
