#!/usr/bin/env bash
# Script displays Holberton School 10 times
# Displays Hi on 9th loop iteration

i="0"

while [ $i -lt 10 ]; do
	if [ $i -eq 9 ]; then
		echo Hi
	fi
	echo Holberton School
	let i+=1
done
