#!/usr/bin/env bash
# Script displays numbers from 1 to 20
# Displays bad luck from China for the 4th loop iteration
# Displays bad luck from Japan for the 9th loop iteration
# Displays bad luck from Italy for the 17th loop iteration

i="1"

while [ $i -lt 21 ]; do
	echo $i
	case "$i" in
		4)
			echo bad luck from China
			;;
		9)
			echo bad luck from Japan
			;;
		17)
			echo bad luck from Italy
			;;
	esac
	let i+=1
done
