#!/usr/bin/env bash
# Script displays the time for 12 hours and 59 minutes
# Displays hours 0 to 12
# Displays minutes 1 to 59

hour="0"
minute="0"

while [ $hour -lt 13 ]; do
	echo Hour: $hour

	minute="1"
	while [ $minute -lt 60 ]; do
		echo $minute
		let minute+=1
	done

	let hour+=1
done
