#!/usr/bin/env bash
# Script displays content of the current directory
# In list format
# Where only the part of the after the first dash is displayed

LIST="$(ls)"

for file in $LIST; do
	echo "$file" | cut -f '2' -d '-'
done
