#!/usr/bin/env bash
# Configures a custom 404 page
FILE=/etc/nginx/sites-available/default
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
sudo sed -i "30i location /redirect_me {\n return 301 https://www.holbertonschool.com/;\n}\n" $FILE
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "33i error_page 404 /custom_404.html;\n location = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}\n" $FILE
sudo service nginx restart
